// playground/vue/src/components/MfmRender.vue
<script lang="ts">
import { h as _h, Component, defineComponent, VNodeArrayChildren } from 'vue'
import { parse } from "mfm-js";
import { NormalRenderer } from "@ikasoba000/every-mfm/src/index"

function h(name: string | Component, props: object, ...children: VNodeArrayChildren) {
  return _h(name, props, children)
}

const renderer = new NormalRenderer(h)

export default defineComponent({
  props: {
    text: {
      type: String,
      required: true
    }
  },
  setup(props) {
    return () => parse(props.text).map(node => renderer.mfmToNode(node))
  }
})
</script>

// playground/react/src/components/MfmRender.tsx
import { createElement, useMemo } from "react"
import { parse } from "mfm-js"
import { NormalRenderer } from "@ikasoba000/every-mfm"

export function MfmRender({ text }: { text: string }) {
  const render = useMemo(() => new NormalRenderer(createElement), [])

  return parse(text).map(node => render.mfmToNode(node))
}
